# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: Chinese website title...
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: Tour
        url: tour
        weight: 10
      - name: 新闻
        url: post
        weight: 20
      - name: 团队
        url: people
        weight: 30
      - name: Events
        url: event
        weight: 40
      - name: Publications
        url: publication
        weight: 50
      - name: Contact
        url: contact
        weight: 60
